"""Build the static English page/scripts from Persian sources; no runtime dependency."""
from pathlib import Path
import re
r=Path(__file__).resolve().parents[1]
translations={
'شاه‌نخ | حس خوب، از تار و پود':'Shahnakh | Feel the difference in every thread',
'دنیای رنگ و لطافت شاه‌نخ در نمایشگاه نساجی و پارچه ایران. برای انتخاب پارچه و شروع همکاری با ما در ارتباط باشید.':'Discover Shahnakh fabrics at the Iran Textile and Fabric Exhibition. Explore texture, try colours and talk to us about your brand.',
'حس خوب، از تار و پود':'A good feeling, woven in',
'رفتن به فرم ارتباط':'Skip to contact form',
'شاه‌نخ، صفحه اصلی':'Shahnakh home',
'نشان شاه‌نخ SNIRAN':'Shahnakh SNIRAN logo',
'منوی اصلی':'Main navigation',
'حس پارچه':'Feel the fabric',
'دنیای رنگ‌ها':'Explore colours',
'دیدار در نمایشگاه':'Meet at the exhibition',
'شروع همکاری':'Work with us',
'حرکت با گوشی':'Enable tilt',
'از نزدیک، متفاوت است':'The difference is in the detail',
'بعضی تفاوت‌ها را':'Some differences',
'باید لمس کرد.':'are felt.',
'بافت، لطافت و ریزش پارچه را از نزدیک ببینید.':'Discover the texture, softness and drape.',
'انتخاب بعدی برند شما، از همین‌جا شروع می‌شود.':'Your brand’s next chapter starts here.',
'کشف حس پارچه':'Discover the fabric',
'چین‌های پهن دورس سه‌نخ سرمه‌ای با پشت نرم و خارخورده':'Deep navy three-thread sweatshirt fabric with a soft brushed reverse',
'نمایشگاه نساجی و پارچه ایران':'Iran Textile & Fabric Exhibition',
'کیفیت را ببینید.':'See the quality.',
'لطافت را':'Feel the',
'احساس کنید.':'softness.',
'برای لباسی که با لمسش، به خاطر می‌ماند.':'For clothing remembered by its touch.',
'نرمی دورس سه‌نخِ پشت‌خارخورده را تجربه کنید.':'Discover the softness of three-thread brushed fleece.',
'برای برند شما، از شاه‌نخ':'Find fabric for your brand',
'اسکرول برای کشف پارچه':'Scroll to explore the fabric',
'ایران، به روایت تار و پود':'Iran, told in threads',
'۰۱ / فراتر از یک پارچه':'01 / More than fabric',
'اول، یک لمس.':'First, a touch.',
'بعد،':'Then,',
'یک انتخاب.':'a choice.',
'پارچه، آغاز شخصیت یک لباس است. در شاه‌نخ، کیفیت بافت و حس خوب پارچه را با دنیایی از رنگ‌ها همراه کرده‌ایم؛ برای آنچه در ذهن شماست.':'Fabric gives clothing its character. At Shahnakh, quality texture and a beautiful feel meet a world of colours, ready for your ideas.',
'درباره پارچه مورد نیازتان صحبت کنیم':'Let’s talk about your fabric needs',
'لطافت در اولین تماس':'Soft from the first touch',
'پشتِ نرم و خارخورده، با حسی گرم و دلنشین در تماس با پوست.':'A soft brushed reverse, with a warm, comfortable feel against the skin.',
'کیفیت در تار و پود':'Quality in every thread',
'پارچه‌های باکیفیت، برای لباسی که با دقت ساخته می‌شود.':'Quality fabrics for thoughtfully made clothing.',
'رنگ، به سلیقه برند شما':'Colour with your brand in mind',
'پالت‌های متنوع برای پیدا کردن رنگی که روایت شما را کامل کند.':'Explore a range of palettes to find a colour that tells your story.',
'۰۲ / رنگی که از شما می‌گوید':'02 / Colour that tells your story',
'یک بافت.':'One texture.',
'هزار حسِ رنگ.':'A world of colour.',
'از آرامش آبی تا جسارت زرشکی؛':'From calming blue to confident crimson,',
'برای هر ایده، دنیایی از انتخاب پیش روی شماست.':'discover possibilities for every idea.',
'یک رنگ را لمس کنید.':'Tap a colour to try it.',
'انتخاب رنگ نمایشی پارچه':'Choose a fabric preview colour',
'آبی شاه‌نخ':'Shahnakh blue','رز اناری':'Pomegranate','سبز یشمی':'Jade green','بنفش یاسی':'Lilac','طلایی عسلی':'Honey gold','سفید شیری':'Milk white','آبی آسمانی':'Sky blue','سبز زیتونی':'Olive','آجری':'Terracotta','قهوه‌ای کاکائویی':'Cocoa','بژ شنی':'Sand','خاکستری زغالی':'Charcoal',
'کدهای TCX پیشنهادی و تطبیق‌ها تقریبی‌اند؛ رنگ نهایی با کارت پنتون و نمونه پارچه تأیید می‌شود.':'TCX references are approximate suggestions. Confirm the final colour against a physical Pantone card and fabric sample.',
'رنگ دلخواه شما':'Your colour',
'کد پنتون پیشنهادی (TCX)':'Suggested Pantone (TCX)',
'کپی کد پنتون':'Copy Pantone code',
'رنگ دلخواه یا یکی از ۱۲ کد پنتون پیشنهادی را انتخاب کنید.':'Choose a colour or enter one of the 12 suggested Pantone codes.',
'با این رنگ، شروع همکاری':'Let’s work with this colour',
'از نزدیک، بافت را ببینید':'Explore the texture up close',
'۱×':'1×',
'برای دیدن بخش‌های مختلف، روی تصویر حرکت کنید یا آن را بکشید.':'Move across the image, drag, or use the arrow keys to explore while zoomed in.',
'بزرگ‌نمایی بافت پارچه':'Fabric texture zoom',
'نمای نزدیک دورس دونخ؛ برای جابه‌جایی نمای بزرگ‌شده از کلیدهای جهت استفاده کنید':'Two-thread loopback fabric close-up; use arrow keys to move the zoomed view',
'دورس دونخ با پشت حلقه‌ای،':'Two-thread loopback fabric,',
'پنتون پیشنهادی · تقریبی':'Suggested Pantone · approximate',
'دورس دونخ · پشت حلقه‌ای':'Two-thread loopback fabric',
'۰۳ / شروع یک همکاری':'03 / Let’s work together',
'تارِ یک آشنایی،':'A first connection.',
'پودِ یک همکاری.':'A shared creation.',
'از نیاز برندتان بگویید.':'Tell us about your brand.',
'برای گفتگو و بررسی پارچه مناسب، با ما در ارتباط باشید.':'Get in touch to explore the right fabric for your needs.',
'تماس با شاه‌نخ':'Call Shahnakh',
'۰۲۱ ۶۶۷۱۸۳۵۵ ↗':'+98 21 66718355 ↗',
'ارتباط با ادمین':'Message our team',
'اینستاگرام':'Instagram',
'بیایید از برند شما شروع کنیم':'Let’s start with your brand',
'رنگ انتخابی شما:':'Your selected colour:',
'همه موارد برای شناخت بهتر نیاز شما هستند.':'All fields help us understand your needs.',
'نام و نام خانوادگی شما':'Your full name',
'نام و نام خانوادگی':'Full name',
'نام مجموعه یا برند':'Your company or brand',
'نام برند':'Brand name',
'شماره موبایل':'Mobile number',
'۰۹۱۲ ۳۴۵ ۶۷۸۹':'0912 345 6789',
'پارچه مصرفی':'Fabric you use',
'نوع پارچه مورد استفاده':'Fabric type',
'مصرف ماهانه':'Monthly consumption',
'(کیلوگرم)':'(kg)',
'مثلاً ۵۰۰':'e.g. 500',
'این فیلد را خالی بگذارید':'Leave this field empty',
'با ثبت فرم، با تماس شاه‌نخ درباره این درخواست موافقم. اطلاعات شما فقط برای پیگیری این ارتباط استفاده می‌شود.':'By submitting, I agree to be contacted by Shahnakh about this enquiry. Your information is used only to follow up on this request.',
'ثبت درخواست همکاری':'Send enquiry',
'بررسی اطلاعات درخواست':'Check enquiry details',
'برای ارسال درخواست با ما تماس بگیرید یا به ادمین پیام دهید؛ ثبت آنلاین هنوز فعال نشده است.':'Please call or message our team to send your enquiry. Online submission is not yet enabled.',
'۰۴ / قرار ما، میان تار و پود':'04 / Meet among the threads',
'جزئیات چین و بافت پارچه آبی':'Close-up of blue fabric texture and folds',
'از پشت صفحه،':'Beyond the screen.',
'به لمس واقعی.':'Into your hands.',
'در نمایشگاه نساجی و پارچه ایران، فرصت داریم از نزدیک آشنا شویم. رنگ‌ها را ببینیم، بافت‌ها را لمس کنیم و درباره نیاز برندتان گفتگو کنیم.':'Meet us at the Iran Textile & Fabric Exhibition. Explore colours, feel the textures and talk with us about what your brand needs.',
'درخواست ارتباط با شاه‌نخ':'Get in touch with Shahnakh',
'بازگشت به بالا':'Back to top',
'برای تغییر رنگ و بررسی فرم، جاوااسکریپت را فعال کنید. تماس با ما:':'Enable JavaScript to try colours and check the form. Call us:',
'۰۲۱۶۶۷۱۸۳۵۵':'+98 21 66718355',
'مرجع پنتون پیشنهادی؛ تطبیق نهایی با نمونه پارچه انجام می‌شود.':'Suggested Pantone reference; confirm the match with a physical fabric sample.',
'پیشنهاد تقریبی از میان ۱۲ مرجع این صفحه؛ جست‌وجوی کامل کاتالوگ پنتون نیست.':'Approximate suggestion from this page’s 12 references, not the full Pantone catalogue.',
'دورس دونخ،':'Two-thread fabric,',
'؛ برای جابه‌جایی نمای بزرگ‌شده از کلیدهای جهت استفاده کنید':'; use the arrow keys to move the zoomed view',
'رنگ دلخواه':'Custom colour',
'این کد در ۱۲ مرجع این نسخه نیست؛ از پیشنهادهای فهرست انتخاب کنید. رنگ فعلی حفظ شد.':'This code is not among these 12 references. Choose a listed suggestion; your current colour is unchanged.',
'کد پنتون ':'Pantone code ',
' کپی شد؛ تطبیق رنگ تقریبی است.':' copied; the colour match is approximate.',
'کد انتخاب شد؛ از گزینهٔ کپی دستگاه استفاده کنید.':'Code selected. Use your device’s Copy command.',
' برابر':' times',
'لطفاً همه موارد فرم را تکمیل کنید.':'Please complete every field.',
'لطفاً یک شماره موبایل معتبر ایران وارد کنید؛ مانند ۰۹۱۲۳۴۵۶۷۸۹.':'Please enter an Iranian mobile number, e.g. 09123456789 or +98 9123456789.',
'مصرف ماهانه را به کیلوگرم و با عددی بیشتر از صفر وارد کنید.':'Enter monthly consumption in kilograms, greater than zero.',
'اطلاعات فرم معتبر است. این نسخه نمایشی است و درخواستی ارسال یا ذخیره نشده است. برای ارتباط با شاه‌نخ از شماره تماس یا لینک ادمین استفاده کنید.':'Your details are valid. Nothing has been sent or stored. Please call or message our team to send your enquiry.',
'در حال ثبت درخواست…':'Sending your enquiry…',
'درخواست شما با موفقیت ثبت شد. از آشنایی با شما خوشحالیم.':'Your enquiry has been received. We look forward to talking with you.',
'ثبت درخواست تأیید نشد. اطلاعات شما در فرم باقی مانده است. لطفاً دوباره تلاش کنید یا با ما تماس بگیرید.':'We could not confirm your enquiry. Your details remain in the form. Please try again or contact us.',
'تقریبی':'approximate',
'شاه‌نخ':'Shahnakh',
}
def translate(s):
    for fa,en in sorted(translations.items(),key=lambda p:-len(p[0])):
        # Escape English apostrophes in script string literals; HTML is handled separately.
        s=s.replace(fa,en)
    return s
s=translate((r/'index.html').read_text(encoding='utf-8'))
s=s.replace('<html lang="fa" dir="rtl">','<html lang="en" dir="ltr">')
s=s.replace('class="language-switch" href="en.html" lang="en" hreflang="en" aria-label="Switch to English">EN','class="language-switch" href="index.html" lang="fa" hreflang="fa" aria-label="تغییر زبان به فارسی">فا')
s=s.replace('assets/app.js','assets/app.en.js').replace('assets/palette.js','assets/palette.en.js')
(r/'en.html').write_text(s,encoding='utf-8')
for name in ['app','palette']:
    s=translate((r/f'assets/{name}.js').read_text(encoding='utf-8'))
    # Typographic apostrophes in translated copy do not terminate JS literals.
    s=s.replace("'fa-IR'","'en-US'")
    if name=='palette':
        # Only the swatch order changes for LTR; physical panning remains left/right.
        a=s.index(' let originX=')
        s=s[:a].replace("event.key==='ArrowLeft'","event.key==='__LEFT__'").replace("event.key==='ArrowRight'","event.key==='ArrowLeft'").replace("event.key==='__LEFT__'","event.key==='ArrowRight'")+s[a:]
    (r/f'assets/{name}.en.js').write_text(s,encoding='utf-8')
print('Built en.html, app.en.js and palette.en.js')
